### ISSUE TITLE
End of the file bug

### ISSUE THREAD

**Issue by MrSnugglesGH** [trych/SmarterLineSwaps#2]
I love this package and hope this helps :)

To reproduce the issue: install SmarterLineMoves package and don't do anything else. Open any file, and select a couple of lines you wish to move. Move the selected lines all the way to the bottom of the file using the functionality that is offered by this package and then keep going beyond the end of the file. Keep going until all you see on your screen are empty lines and the selected text you are moving. Than stop and move your selected lines back up. It doesn't matter if you move the selected text up line by line (that way it is easier to catch the bug in my opinion) or just keep holding the keyboard combo.

Expected behavior: as I move my lines up, I get to see a couple of lines (5 lines is default, I believe) above those I am moving.

What actually happens: lines I am moving reach the top of the screen and I get to see none of the lines above those I am moving. Then I keep going up. At some point there is a transition of behavior such that suddenly I get the expected behavior, or in other words, at some point window snaps and I get to see 5 lines above those I am moving up. This jerky behavior when transitioning between no lines above and 5 lines above makes user experience less fluid.

Edit: Here is a video example of what I described above. At around 00:19 you can see the transition from no lines to 5 lines above those I am moving.

https://user-images.githubusercontent.com/88436666/147355298-b96fdab7-366c-4756-8099-c1cdefcc7b9a.mp4

Edit 2: if _"scroll_past_end": false_ is set then there is no weird behavior. However I like that setting to be set as _true_ and it set that way by default, so that's why there's a problem with this package.

**Comment by trych** [comment]
Hey, thanks a lot, glad people find this useful. :)
The issue was an edge case indeed, but luckily easy to fix. The fixed version should auto load via Package Control sometime soon.

**Comment by MrSnugglesGH** [comment]
Oh its very useful! Thank you for this package and thank you for your continued support! Just got the message on sublime that this package was updated, so I came here to offer a bit more feedback after playing with it for some time. 

The bug in this thread has indeed been solved. However, when I move a block of text, in the down direction, I get stuttery behavior when I reach the bottom of my screen. It seems that instead of text staying static at the bottom and the 'background' text moving up line by line as I press the down key, what actually happens is that on the down key press the selected text moves one line down, and on the second down key press I get both the selected text and the background moving up. This doesn't happen when I'm moving a block of text in the upward direction. It's much easier to see this in the first part of the attached video.

The second bug isn't really a bug, but more like a feature request. The thing is, if you have folded comments, then you have to wait for the block of text you are moving to move line by line through each comment, even though all those lines are invisible from your point of view, as all you see are three dots inside a yellow box in only one line as a sign of a folded comment. It would be nice if the text you are moving treated folded comments as if they were only one line long regardless of how long they really are. You can see this in the second part of the attached video. I use Fold Comments package to fold all the comments on key combo, so that's what you see in the video.

https://user-images.githubusercontent.com/88436666/147911385-4df19954-a1d7-4e59-8a06-2a7fc553950f.mp4

I pressed up/down keys at the same steady rate after I folded all the comments. But, as you can see in the video, there is noticeable delay as I am waiting for the block of text to move through all the invisible lines of the folded comment. Second comment is only one line long so that's why there's no delay. I think it would be a much smoother experience if folded comment length was ignored and all comments were treated as if they were only one line long.

EDIT: I figured out that the problem (stutter) is only there when you are in the "Distraction Free" view mode. The problem goes away in full-screen and non full-screen view mode (or whatever the default mode is called). Still, as I work pretty much exclusively in the Distraction Free view mode, I would really appreciate it if you could do something so that it feels as smooth as it already does in other view modes :D

**Comment by trych** [comment]
Hi @MrSnugglesGH thanks for giving continued feedback.
Unfortunately, the video seems to be broken, could you try to re-upload it?

The part with the folded comments was actually brought up a few times already and is on my ToDo-List. :) It's a bit more complicated though, so I don't know, when I will find the time to tackle this.

**Comment by MrSnugglesGH** [comment]
If I use firefox to view this page then I get the message: "Video can't be played because the file is corrupt." 

Using Chrome however, let's me play the video without any problems (!?) Weird... don't know why that is... but try using some other web browser and you should be able to watch that video. Microsoft Edge works as well...

And no worries about the folded comment thing... would be nice to have that as an option, but the package is already a huge improvement compared to the default behavior of ST4. :D

**Comment by MrSnugglesGH** [comment]
Try this video if the one above can't be played in other browsers:

https://user-images.githubusercontent.com/88436666/148213442-ff60f186-ba01-43a2-a411-1ed7ae81dca8.mp4

This video is even better in demonstrating what the problem really is. At the start of the video you can see that everything works fine - there is no stuttering when I move a block of text downward. 

However, later on, you can see stuttering when I do the exact same thing as before. At some point of the video you can see me moving the block of text line by line by repeatedly pushing the down arrow key instead of just holding the down key. That way it's clear to see that on a single press of 'down arrow key' the block of text moves by one line down. However, on the next 'down arrow key' both the background and the block of text move up by one line. This pattern repeats over and over again if I just hold the down arrow key, which leads to the apparent stuttering.

EDIT: This video can't also be played in firefox, but edge and chrome do allow playback...

**Comment by trych** [comment]
Thanks, was able to watch the video in Chrome. I cannot currently reproduce the bug on my machine. I work on a Mac though, it looks like you are working under Windows, right? Might give this another try on my Windows machine later.

**Comment by MrSnugglesGH** [comment]
I'm on linux (Ubuntu).

**Comment by trych** [comment]
Ah, okay, apologies. I currently have no possibility to test this under Linux. However, I will give it a test under Windows, who knows maybe I will encounter the same problem.

**Comment by MrSnugglesGH** [comment]
I just tried this on another laptop (Windows). I did a fresh install of ST4. Then I installed the package manager and SmarterLineMoves. Nothing else.

As on my ubuntu machine, there doesn't seem to be any problem in full screen mode. 

In Distraction Free mode there is stuttering similar to the one I experienced on my Ubuntu machine. The only difference is that stuttering appears when you move a block of text up instead of down.

Windows:

- Up: Stutter
- Down: No stutter

Ubuntu:

- Up: No stutter
- Down: Stutter

Sometimes there is no stutter, so just try a couple of times. Most of the time there will be stuttering going on. 

Also try testing this in a file that has at least as many lines as can fit on your screen.

EDIT: Actually, I believe I discovered something. Font size matters. 

Font size:

- 10: no stutter
- 11: no stutter
- 12: stutter (downward; rarely)
- 13: stutter (downward; almost always)
- 14: no stutter

I even got stuttering in the up direction on my ubuntu machine, but forgot to check at what font size. Try changing font size on your Mac. Maybe then stuttering appears.
