### ISSUE TITLE
Windows key bindings override macOS bindings

### ISSUE THREAD

**Issue by jtran** [trych/SmarterLineSwaps#3]
Hi, thank you for making this package.

By default on macOS, Control+Shift+Up and Control+Shift+Down create multiple cursors using the following in `Default (OSX).sublime-keymap`.

```json
{ "keys": ["ctrl+shift+up"], "command": "select_lines", "args": {"forward": false} },
{ "keys": ["ctrl+shift+down"], "command": "select_lines", "args": {"forward": true} },
```

However, when I install this package, these key bindings get overridden and do line swapping instead.  Can this package only override based on the platform?

**Comment by lapinvert** [comment]
+1 I had the same issue, I've made a PR above that solves it : )

**Comment by trych** [comment]
Hi @jtran, sorry I didn't look into this sooner. @lapinvert lapinvert fixed this now. If you have installed it via PackageControl, then your package should update automatically soon-ish. :)
